In [1]:
#1.	Write a Python Program to Add Two Matrices?
# Program to add two matrices
# using numpy

import numpy as np

X = [[1,2,3],
	[4 ,5,6],
	[7 ,8,9]]

Y = [[9,8,7],
	[6,5,4],
	[3,2,1]]

result = np.array(X) + np.array(Y)

print(result)


[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [3]:
#2.	Write a Python Program to Multiply Two Matrices?
result = np.multiply(np.array(X) , np.array(Y))

print(result)


[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [4]:
#3.	Write a Python Program to Transpose a Matrix?
# import the important module in python
import numpy as np
			
# make matrix with numpy
mt = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
			
# applying matrix.transpose() method
tmt = mt.transpose()
	
print(tmt)


[[ 4 12  4]
 [ 1  3  5]
 [ 9  1  6]]


In [10]:
#4.	Write a Python Program to Sort Words in Alphabetic Order?
s="This is the program to demonstrate the sorting of words lexicographyicaly "
lst=[x for x in s.split(" ")]
lst.sort()
s=" ".join(lst)
print(s)

 This demonstrate is lexicographyicaly of program sorting the the to words


In [13]:
#5.	Write a Python Program to Remove Punctuation From a String?
test_str = "Gfg, is best : for ! Geeks ;"

# printing original string
print("The original string is : " + test_str)

# initializing punctuations string
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

# Removing punctuations in string
# Using loop + punctuation string
for ele in test_str:
	if ele in punc:
		test_str = test_str.replace(ele, "")

# printing result
print("The string after punctuation filter : " + test_str)


The original string is : Gfg, is best : for ! Geeks ;
The string after punctuation filter : Gfg is best  for  Geeks 
